connection: icepique
noXsd: false
defaultIdMethod: native
package: plugins.iceCrontabPlugin.lib.model
encoding: utf8

classes:
  Crontab:
    phpName: iceModelCrontab
    columns:
      id:  ~
      context:       { type: char, sqlType: "ENUM('global', 'icepique', 'autohop', 'bezplatno', 'burzo', 'hitimoti', 'netbox', 'torena')", default: global, required: true }
      minute:        { type: char, size: 2, required: true, default: 01 }
      hour:          { type: char, size: 2, required: true, default: 05 }
      month:         { type: char, size: 2, required: true, default: '*' }
      day_of_week:   { type: char, size: 2, required: true, default: '*' }
      day_of_month:  { type: char, size: 2, required: true, default: '*' }
      function_name: { type: varchar, size: 255, required: true, primaryString: true }
      parameters:    { type: varchar, size: 255, required: false }
      description:   { type: longvarchar, required: false }
      priority:      { type: integer, sqlType: "SMALLINT UNSIGNED", required: true, default: 1 }
      is_active:     { type: boolean, sqlType: "BOOL", default: true }
      updated_at:  ~
      created_at:  ~
